Refactor modality selection and disable breakpoint
Replaced target_index with EMB_INDEX for modality selection and commented out breakpoint to prevent crashes.

Left the modality selector intact, but added guardrails (in our workflow) to explain the “single class” error experienced in anaconda environment:
ValueError: ... needs samples of at least 2 classes happened because step-0 used temporary dummy “Wake” labels to initially test the whole pipeline.